### ISSUE TITLE
MapQuest in the code samples

### ISSUE THREAD

**Issue by Bear4** [acanimal/thebookofopenlayers3#5]
Hi!
Changing base map in examples at: http://www.acuriousanimal.com/thebookofopenlayers3/index.html
would be nice.

Thanks for book and code samples.

**Comment by acanimal** [comment]
what do you mean @Bear4 ? There are samples that uses different maps, for example: http://www.acuriousanimal.com/thebookofopenlayers3/chapter02_02_layer_stack.html

Thanks !!!
